### ISSUE TITLE
reload not working with gulp 4

### ISSUE THREAD

**Issue by boxertech** [Quramy/electron-connect#34] opened 2016-05-06 17:04 UTC
When I call electron.reload the terminal shows 'bound ' ... , it stops there, and nothing reloads. The code calling reload is:

    gulp.watch(paths.appHtml, gulp.series('copy:index', 'copy:spa-for-electron', electron.reload));

electron.restart works in place of reload above, but reload is the correct action here.

**Comment by boxertech** [comment] 2016-05-06 17:15
I have no id's specified, so electron-connect is doing a broadcast('reload')

**Comment by Quramy** [comment] 2016-05-11 11:04
Sorry, I am not familiar with gulp 4. Can you reproduce with gulp 3.9 ?

**Comment by applee** [comment] 2016-05-24 15:13
I think it's none of gulp's version business, I'm using gulp 3.9.1 and having the same problem.

**Comment by ssreekanth** [comment] 2016-05-26 18:27
@applee @boxertech reload() works for me. If you can create a gist to reproduce the issue, then we can look into it.

**Comment by ssreekanth** [comment] 2016-08-14 06:49
closing this issue, as there is no reponse from the issue reporter. If you are still seeing the issue, please re-open it and provide the steps to recreate the issue.

**Closed by ssreekanth** 2016-08-14 06:49 UTC

**Comment by hetsch** [comment] 2017-02-18 14:30
I've hit the same problem today. What seems to work for me is rather than passing `gulp.series` directly the function `electron.reload` create wrapper function that calls `electron.reload`, `start` or `restart` in its body.

    function restart() {
        livereload.restart('--enable-logging', function(state) {
             if (state === 'restarted' || state === 'restarting') {
                done(null);
             } else {
                done(`Got an unexpected state while restarting electron-connect server. State <${state}>`);
           }
        });
    }

This seems to work for the restarting part. Sadly `--enable-logging` seems to have no effect.

**Comment by novalex** [comment] 2018-04-05 05:11
I've had the same issue, and solved it by using separate functions with "done()" for restarting and reloading as in @hetsch's comment. I've added "done" as a parameter to the functions, because the version with the decorator triggered a syntax error. Here's the relevant part of my gulpfile:

```
gulp.task( 'serve', gulp.series( 'build', gulp.parallel( 'watch', () => {
	electron.start( () => {
		gulp.watch( paths.dist.build + '/index.js', restart )
		gulp.watch( [ paths.dist.build + '/js/*.js', paths.dist.build + '/css/app.css' ], reload )
	})
} ) ) )

function restart( done ) {
	electron.restart( '--enable-logging', function( state ) {
		if ( state === 'restarted' || state === 'restarting' ) {
			done( null );
		} else {
			done( 'Unexpected state while restarting electron-connect server. State ' + state );
		}
	});
}

function reload( done ) {
	electron.reload();
	done( null );
}
```
