### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by niftylettuce** [Quramy/electron-connect#23] opened 2016-01-13 03:26 UTC
```log
[24840:0112/222627:INFO:CONSOLE(141)] "Uncaught Error: connect ECONNREFUSED 127.0.0.1:30080", source: events.js (141)
[24840:0112/222627:INFO:CONSOLE(141)] "Uncaught Error: socket hang up", source: events.js (141)
```

**Comment by niftylettuce** [comment] 2016-01-13 03:26
Won't work

**Comment by otissv** [comment] 2016-02-28 17:45
I have this issue too

`Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:30080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)`

**Comment by lvchaoin** [comment] 2016-05-21 04:37
+1

**Comment by minardimedia** [comment] 2016-07-05 23:30
+1

**Comment by ngprasad** [comment] 2016-07-13 18:23
+1

**Comment by ngprasad** [comment] 2016-07-15 00:39
Any updates on this?

**Comment by minardimedia** [comment] 2016-07-15 00:50
Hi I was getting this error also, I fix it adding the client in the main.js  instead of adding it on the index.html. In the documentation they point you can do it this way. Also I think I was missing to start electron connect in my gulfile

main.js

`
const client = require('electron-connect').client;

function createWindow () {
  mainWindow = new BrowserWindow({width: 1235, height: 670})
  mainWindow.loadURL(`file://${__dirname}/index.html`)
  client.create(mainWindow);
  mainWindow.webContents.openDevTools()
  mainWindow.on('closed', function () {
    mainWindow = null
  })
}
`
 gulpfile.js

`
var electron = require('electron-connect').server.create();

.........

gulp.task('default', ['css', 'scripts'], function () {
    electron.start();
    gulp.watch("src/scss/*/*.scss", ['css']);
    return buildScript('main.js', true);
});

`

**Comment by ssreekanth** [comment] 2016-08-14 06:45
@niftylettuce can't reproduce. closing it for now. If you are still seeing this issue, please re-open and provide us with steps to recreate the issue.

**Closed by ssreekanth** 2016-08-14 06:45 UTC

**Comment by chenqunfeng** [comment] 2016-08-29 11:05
I met it when I want to open my .exe.
And this is my solution.

**main.js**
```
function mainWindowFun() {
    debug && (devToolsWidth = 1000)

    mainWindow = new BrowserWindow({
        frame: false,
        height: 500,
        width: 370 + devToolsWidth,
        resizable: false
    })

    // Open the DevTools.
    debug && (mainWindow.webContents.openDevTools())

    mainWindow.loadURL('file://' + __dirname + '/app/html/index.html');

    // debug and client.create(mainWindow)
}
```
what you need is to annotate "debug and client.create(mainWindow)"

Because after you packager it, you don't have a commandWin to connect with the client.
That is the reason why its socket hang up

**Comment by asifashraf** [comment] 2017-10-15 03:09
Uncaught Error: connect ECONNREFUSED 127.0.0.1:30080
facing the same issue, Followed the instruction and made no mistake
